### ISSUE TITLE
urllib2/socket crash with current CSS opibuilder

### ISSUE THREAD

**Issue by kasemir** [PythonScanClient/PyScanClient#18]
Current CSS opibuilder re-uses the same jython instance if a display is re-opened, i.e. a script is only compiled once.

When an *.opi file has an action button with script to submit a scan, this works only when the *.opi is opened the first time. After closing it and re-opening it, the error shown below results.

Looks similar to http://bugs.jython.org/issue2207, but the jython in CSS seems to include  	Lib/_socket.py and Lib/test/test_socket.py with the updates mentioned in there.

A workaround might be to update `scan_client.__do_request()` to close the connection such that a re-use (and then crash) is avoided.

````
org.python.netty.util.concurrent.DefaultPromise (execute) - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at org.python.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728)
	at org.python.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671)
	at org.python.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641)
	at org.python.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138)
	at org.python.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
	at org.python.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at _socket$py._handle_channel_future$70(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:778)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.core.PyFunction.__call__(PyFunction.java:461)
	at org.python.core.PyObject._callextra(PyObject.java:601)
	at _socket$py.handle_exception$30(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:366)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:161)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at _socket$py._connect$77(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:864)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at _socket$py.connect$80(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:888)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.PyObject._callextra(PyObject.java:601)
	at _socket$py.meth$117(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:1367)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.core.PyFunction.__call__(PyFunction.java:461)
	at org.python.modules._functools.PyPartial.partial___call__(PyPartial.java:124)
	at org.python.modules._functools.PyPartial.__call__(PyPartial.java:79)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at _socket$py.create_connection$131(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py:1507)
	at _socket$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/_socket.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at httplib$py.connect$24(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:796)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at httplib$py.send$26(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:826)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at httplib$py._send_output$28(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:854)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at httplib$py.endheaders$31(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:997)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at httplib$py._send_request$34(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:1035)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:187)
	at httplib$py.request$32(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py:1001)
	at httplib$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/httplib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:187)
	at urllib2$py.do_open$97(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py:1208)
	at urllib2$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at urllib2$py.http_open$101(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py:1214)
	at urllib2$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.PyObject._callextra(PyObject.java:601)
	at urllib2$py._call_chain$36(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py:379)
	at urllib2$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:187)
	at urllib2$py._open$38(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py:426)
	at urllib2$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at urllib2$py.open$37(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py:412)
	at urllib2$py.call_function(/home/controls/css/sns-css-4.1.0/plugins/org.python.jython_2.7.0/Lib/urllib2.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:161)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at scan.client.scanclient$py._ScanClient__do_request$4(/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py:100)
	at scan.client.scanclient$py.call_function(/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:188)
	at org.python.core.PyFunction.__call__(PyFunction.java:446)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at scan.client.scanclient$py._ScanClient__submitScanXML$10(/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py:206)
	at scan.client.scanclient$py.call_function(/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py)
	
2015-07-10 14:12:57.823 WARNING [Thread 1] org.python.core.PyReflectedFunction (__call__) - Alignment Scan: Failed to reach scan server at 10.111.34.130:4810: [Errno -1] Unmapped exception: java.util.concurrent.RejectedExecutionException: event executor terminated
Traceback (most recent call last):
  File "<script>", line 24, in <module>
  File "/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py", line 179, in submit
    result = self.__submitScanSequence(CommandSequence(cmds), quoted_name)
  File "/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py", line 217, in _ScanClient__submitScanSequence
    return self.__submitScanXML(cmdSeq.genSCN(),scanName)
  File "/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py", line 205, in _ScanClient__submitScanXML
    r = self.__do_request(url, 'POST', scanXML)
  File "/home/controls/css/PyScanClient/build/lib/scan/client/scanclient.py", line 95, in _ScanClient__do_request
    raise Exception("Failed to reach scan server at %s:%d: %s %s" % (self.__host, self.__port, e.reason, str(e)))
````

**Comment by kasemir** [comment]
problem can be duplicated with a display that has single button, invoking this script that submits a bogus scan to a scan server on 'localhost':
````
from scan.client.scanclient import ScanClient
from org.eclipse.jface.dialogs import MessageDialog
client = ScanClient()
id = client.submit("<commands><comment><text>Test</text></comment></commands>")
MessageDialog.openInformation(None, "Info", "Submitted %d" % id)
````

Try once, then close display, open other display that happens to use script, try again
-> `java.util.concurrent.RejectedExecutionException: event executor terminated`

**Comment by kasemir** [comment]
Problem reappeared, this time with scripts that are triggered by PVs and not an Action Button.

See also http://stackoverflow.com/questions/32239955/why-does-this-jython-loop-fail-after-a-single-run

**Comment by kasemir** [comment]
Problem can be duplicated with *.opi file that invokes this script on a PV like "sim://ramp(0, 10, 1, 3.0)":
```
# Enable logging from org.python.jython_2.7.0.release/Lib/_socket.py:
import _socket
import logging
logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger("_socket")
log.setLevel(level=logging.DEBUG)

# Submit simple scan
from scan.client.scanclient import ScanClient
from scan.commands.delay import Delay
client = ScanClient()
cmds = [ Delay(1.0) ]
client.submit(cmds, "Test")
```

When display is executed the first time, all is well, but when the display is closed, it shows 
```
DEBUG:_socket:Closed socket
DEBUG:_socket:Shutting down thread pool...
DEBUG:_socket:Shut down thread pool
```

When display is re-opened, `_socket.connect()` fails because its `NIO_GROUP` thread pool was shut down.

**Comment by kasemir** [comment]
When the BOY opens a display with a script, `JythonScriptStore` calls
````
         interp = PythonInterpreter.threadLocalStateInterpreter(state.getDict());
````
That `interp` then compiles and executes the script. When the display is closed, `JythonScriptStore` closes and disposes the interpreter.

Turns out that the next time the same display is opened and another script is compiled and executed, it receives the same `_socket.py instance`, whos `NIO_GROUP` thread pool was shut down at the end of the first display execution.

Possible fix within the script is to re-create the thread pool:
````
import sys, _socket
if _socket.NIO_GROUP.isShutdown():
    print "RE-CREATEING NIO_GROUP"
    _socket.NIO_GROUP = _socket.NioEventLoopGroup(2, _socket.DaemonThreadFactory("PyScan-Netty-Client-%s"))
    sys.registerCloser(_socket._shutdown_threadpool)
````
